# Generated by Django 5.1.7 on 2025-04-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_payment_photo_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
